/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/1920s_table_lamps_type_a.glb --typescript --transform
Author: Mad_Lobster_Workshop (https://sketchfab.com/Mad_Lobster_Workshop)
License: COPYRIGHT TO Mad_Lobster_Workshop
Source: https://sketchfab.com/3d-models/1920s-table-lamps-type-a-fb7475ef551c46f9b4b2b28d96d31dfc
Title: 1920s Table Lamps Type A
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";

const MODEL_URL = "/1920s_table_lamps_type_a-transformed.glb";

export function Model(props: ThreeElements["group"]) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials } = useGLTF(MODEL_URL) as any;
  // The source scene ("1920s Table Lamps Type A", plural) modeled a row of
  // several lamps: Object_4 is a merged batch of ~4-5 of them, Object_12 and
  // Object_14 are two more single lamps sharing the same geometry under
  // different material variants. The installation only wants one lamp, so
  // only Object_14 (the lacquered variant) is kept, recentered to its own
  // origin instead of its old offset within that wider row.
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_14.geometry} material={materials["1920s_Table_Lamp_Type_A_Wood_Lacquer"]} />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
