/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bedside_table.glb -T 
Files: bedside_table.glb [2.88MB] > G:\Projects\Cuib-darte\cuib\src\assets\bedside_table-transformed.glb [253.18KB] (91%)
Author: jspurlin (https://sketchfab.com/jspurlin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bedside-table-0cbed499cebb4c889738c20ea1ed52d5
Title: Bedside Table
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Table(props) {
  const { nodes, materials } = useGLTF("/bedside_table-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Bedside_Table}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.Lamp_Stand}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/bedside_table-transformed.glb");
