/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/book_animated_book__historical_book.glb --typescript --transform
Author: khalidrahmanhanify (https://sketchfab.com/khalidrahmanhanify)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-animated-book-historical-book-097f8683aa5d4c9da1530d6119c20ac3
Title: Book animated book , historical book
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { LoopPingPong, type Group } from "three";

const MODEL_URL = "/book_animated_book__historical_book-transformed.glb";

type BookModelProps = ThreeElements["group"] & {
  /** Multiplies the baked clip's playback rate so instances shown together
   *  (e.g. a grid) don't turn their pages in lockstep. 1 = authored speed. */
  speed?: number;
};

export function Model({ speed = 1, ...props }: BookModelProps) {
  const group = useRef<Group>(null);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials, animations } = useGLTF(MODEL_URL) as any;
  const { actions } = useAnimations(animations, group);

  // The scan ships with one baked clip (cover opening, pages turning) that
  // was never played — the model just sat on its first frame. Run it as a
  // looping idle instead, with each mounted instance starting at a random
  // point in the clip and at its own speed so multiple books on screen
  // don't flip in lockstep. Ping-ponging (rather than repeating) plays the
  // pages forward then back instead of snapping to the start each time it
  // finishes.
  useEffect(() => {
    const action = Object.values(actions)[0];
    if (!action) return;

    action.setLoop(LoopPingPong, Infinity).reset().play();
    action.timeScale = speed;
    action.time = Math.random() * action.getClip().duration;

    return () => {
      action.stop();
    };
  }, [actions, speed]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode" scale={1.599}>
          <group name="pine_34" position={[0.065, 0.115, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.09, 0.025, 1]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials["Material.003"]} />
          </group>
          <group name="cover-r_35" position={[0.09, 0.025, 0]} scale={[0.71, 0.025, 1]}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials["Material.003"]} />
          </group>
          <group name="cover-l_36" position={[0.09, 0.205, 0]} scale={[0.71, 0.025, 1]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials["Material.003"]} />
          </group>
          <group name="paper_39" position={[0.09, 0.03, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials["Material.001"]} />
          </group>
          <group name="paper001_40" position={[0.09, 0.035, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} />
          </group>
          <group name="paper002_41" position={[0.09, 0.04, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} />
          </group>
          <group name="paper003_42" position={[0.09, 0.045, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} />
          </group>
          <group name="paper004_43" position={[0.09, 0.05, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_0} />
          </group>
          <group name="paper005_44" position={[0.09, 0.056, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_0} />
          </group>
          <group name="paper006_45" position={[0.09, 0.061, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_0} />
          </group>
          <group name="paper007_46" position={[0.09, 0.066, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material_0} />
          </group>
          <group name="paper008_47" position={[0.09, 0.071, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} />
          </group>
          <group name="paper009_48" position={[0.09, 0.076, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_0} />
          </group>
          <group name="paper010_49" position={[0.09, 0.081, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} />
          </group>
          <group name="paper011_50" position={[0.09, 0.086, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} />
          </group>
          <group name="paper012_51" position={[0.09, 0.091, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_0} />
          </group>
          <group name="paper013_52" position={[0.09, 0.096, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} />
          </group>
          <group name="paper014_53" position={[0.09, 0.102, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_0} />
          </group>
          <group name="paper015_54" position={[0.09, 0.107, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_0} />
          </group>
          <group name="paper016_55" position={[0.09, 0.112, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials["Material.005"]} />
          </group>
          <group name="paper017_56" position={[0.09, 0.117, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials["Material.006"]} />
          </group>
          <group name="paper018_57" position={[0.09, 0.122, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_0} />
          </group>
          <group name="paper019_58" position={[0.09, 0.127, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_0} />
          </group>
          <group name="paper020_59" position={[0.09, 0.132, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_0} />
          </group>
          <group name="paper021_60" position={[0.09, 0.137, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} />
          </group>
          <group name="paper022_61" position={[0.09, 0.142, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} />
          </group>
          <group name="paper023_62" position={[0.09, 0.148, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_0} />
          </group>
          <group name="paper024_63" position={[0.09, 0.153, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
          </group>
          <group name="paper025_64" position={[0.09, 0.158, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} />
          </group>
          <group name="paper026_65" position={[0.09, 0.163, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
          </group>
          <group name="paper027_66" position={[0.09, 0.168, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} />
          </group>
          <group name="paper028_67" position={[0.09, 0.173, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} />
          </group>
          <group name="paper029_68" position={[0.09, 0.178, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
          </group>
          <group name="paper030_69" position={[0.09, 0.183, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} />
          </group>
          <group name="paper031_70" position={[0.09, 0.188, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
          </group>
          <group name="paper032_71" position={[0.09, 0.194, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
          </group>
          <group name="paper033_72" position={[0.088, 0.196, 0]} rotation={[Math.PI / 2, 0.01, 0]} scale={[0.71, 1, 1]}>
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_0} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
