/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house_plants_hanging_pot.glb -T 
Files: house_plants_hanging_pot.glb [13.54MB] > G:\Projects\Cuib-darte\cuib\src\assets\house_plants_hanging_pot-transformed.glb [1.65MB] (88%)
Author: monahu (https://sketchfab.com/monahu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-plants-hanging-pot-be9ff79548ea45e08e3cead756ebd3ab
Title: House Plants Hanging Pot
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Plant(props) {
  const { nodes, materials } = useGLTF(
    "/house_plants_hanging_pot-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plant_hanging_N050922_Ceramic_0.geometry}
        material={materials.Ceramic}
        position={[-0.026, -9.217, 0.078]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plant_hanging_N050922_Metal_0.geometry}
        material={materials.Metal}
        position={[-0.026, -9.217, 0.078]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plant_hanging_N050922_Stem_0.geometry}
        material={materials.Stem}
        position={[-0.026, -9.217, 0.078]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plant_hanging_N050922_Ground_0.geometry}
        material={materials.Ground}
        position={[-0.026, -9.217, 0.078]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plant_hanging_N050922_Leaf001_0.geometry}
        material={materials["Leaf.001"]}
        position={[-0.026, -9.217, 0.078]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/house_plants_hanging_pot-transformed.glb");
