/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/red_wine_glass.glb --typescript --transform
Author: Rylae Shylna (https://sketchfab.com/risteralline)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-wine-glass-ad6a40bbcf50435bbd41411ece4b9dbe
Title: Red Wine Glass
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";

const MODEL_URL = "/red_wine_glass-transformed.glb";

export function Model(props: ThreeElements["group"]) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials } = useGLTF(MODEL_URL) as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.WineGlassMerged_WineGlassMerged_0.geometry} material={materials.WineGlassMerged} position={[0, 0.086, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.565} />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
