/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/typewriter.glb --typescript --transform
Author: freddy1231 (https://sketchfab.com/freddy1231)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/typewriter-0b6766c2df0e4901b8c387283d544027
Title: Typewriter
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";

const MODEL_URL = "/typewriter-transformed.glb";

export function Model(props: ThreeElements["group"]) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { nodes, materials } = useGLTF(MODEL_URL) as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Neri_Royal_typewriter_Plastic_0.geometry} material={materials.Royal_typewriter_Plastic} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Metal_Chrome_0.geometry} material={materials.Metal_Chrome} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Rubber_0.geometry} material={materials.Royal_typewriter_Rubber} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Buttons_0.geometry} material={materials.Royal_typewriter_Buttons} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Metal_black_0.geometry} material={materials.Royal_typewriter_Metal_black} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Measure_0.geometry} material={materials.Royal_typewriter_Measure} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Tape_0.geometry} material={materials.Royal_typewriter_Tape} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Neri_Royal_typewriter_Paper_0.geometry} material={materials.Royal_typewriter_Paper} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes["Targa_Material_#51_0"].geometry} material={materials.Material_51} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Logo_Royal_typewriter_Label_0.geometry} material={materials.Royal_typewriter_Label} position={[0, 0.322, 0.263]} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes["Bodymy01_17_-_Default_0"].geometry} material={materials["17_-_Default"]} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
